version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: smm_app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  parsers:
    container_name: smm_parsers
    build:
      context: .
      dockerfile: Dockerfile.parsers
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
